### PR TITLE
Support gradle task cache

### PR DESCRIPTION
**Pull request by tnielens-centrica**
Implements #71.

### CODE REVIEW

**Review by skiesewetter-intershop — APPROVED** [review]

**Comment by tnielens** [comment]
@skiesewetter-intershop could people at intershop review the propositions in #71 and #72?

**Comment by tnielens** [comment]
@skiesewetter-intershop @m-raab would you mind having a look at these PRs. I think they good improvements.

**Review by skiesewetter-intershop — APPROVED** [review]

**Comment by skiesewetter-intershop** [comment]
> @skiesewetter-intershop can you cover this one too?

@tnielens I can if you resolve the conflicts in prior.

**Comment by tnielens-centrica** [comment]
@skiesewetter-intershop done

**Pull request merged**
