### PR TITLE
Support configuration cache

### PR DESCRIPTION
**Pull request by tnielens-centrica**
Implements #70, addresses #59.

### CODE REVIEW

**Review by skiesewetter-intershop — APPROVED** [review]
@tnielens: Thank you for your contribution.

**Comment by cschoell** [comment]
Will this be merged? It would be awesome to have a version with this fix included.

**Comment by tnielens-centrica** [comment]
@skiesewetter-intershop periodical ping :)

**Comment by skiesewetter-intershop** [comment]
> Will this be merged? It would be awesome to have a version with this fix included.

@cschoell You can merge it as soon as the conflicts are resolved.

**Comment by cschoell** [comment]
> > Will this be merged? It would be awesome to have a version with this fix included.
> 
> @cschoell You can merge it as soon as the conflicts are resolved.

I think you meant @tnielens-centrica , right?

**Comment by skiesewetter-intershop** [comment]
> > > Will this be merged? It would be awesome to have a version with this fix included.
> > 
> > 
> > @cschoell You can merge it as soon as the conflicts are resolved.
> 
> I think you meant @tnielens-centrica , right?

@cschoell: The question "Will this be merged?" came from you.

**Comment by cschoell** [comment]
> > > > Will this be merged? It would be awesome to have a version with this fix included.
> > > 
> > > 
> > > @cschoell You can merge it as soon as the conflicts are resolved.
> > 
> > 
> > I think you meant @tnielens-centrica , right?
> 
> @cschoell: The question "Will this be merged?" came from you.

That's true, but I don't know how I can merge it? I don't think I have the rights to do that.

**Comment by cschoell** [comment]
It says 
"Only those with [write access]to this repository can merge pull requests."

I'm not sure if @tnielens or me can merge this at all?

**Comment by cschoell** [comment]
Thanks @skiesewetter-intershop :)

**Pull request merged**
